import canonicalLaneMathlib.AdmissibleClass
import HautevilleHouse.DiscreteSubgroupsLieGroupsLemmaCanonicalLaneLean.DiscreteSubgroupStructure

/-!
# Margulis Lemma Package

This module captures the Margulis lemma: a discrete subgroup generated by
small elements is virtually nilpotent.
-/

namespace HautevilleHouse
namespace DiscreteSubgroupsLieGroupsLemmaCanonicalLaneLean

structure MargulisLemmaPackage (G : Type*) [LieGroupStructure G] (Γ : DiscreteSubgroup G) where
  epsilonExists : ℝ
  epsilonPositive : epsilonExists > 0
  smallGenerationSet : Set G
  smallGenerationSetSubset : smallGenerationSet ⊆ Γ.carrier
  smallGenerationDiameter : Diameter smallGenerationSet < epsilonExists
  conclusion : IsVirtuallyNilpotent (Subgroup.generate smallGenerationSet)

structure MargulisLemmaEvidence (G : Type*) [LieGroupStructure G] (Γ : DiscreteSubgroup G) (M : MargulisLemmaPackage G Γ) where
  epsilonPositiveClosed : M.epsilonPositive
  smallGenerationDiameterClosed : M.smallGenerationDiameter
  conclusionClosed : M.conclusion

def MargulisLemmaClosed (G : Type*) [LieGroupStructure G] (Γ : DiscreteSubgroup G) (M : MargulisLemmaPackage G Γ) : Prop :=
  M.epsilonPositive ∧ M.smallGenerationDiameter ∧ M.conclusion

theorem margulis_lemma_closed_from_evidence
    (G : Type*) [LieGroupStructure G] (Γ : DiscreteSubgroup G) (M : MargulisLemmaPackage G Γ)
    (E : MargulisLemmaEvidence G Γ M) : MargulisLemmaClosed G Γ M := by
  exact And.intro E.epsilonPositiveClosed (And.intro E.smallGenerationDiameterClosed E.conclusionClosed)

end HautevilleHouse.DiscreteSubgroupsLieGroupsLemmaCanonicalLaneLean
end HautevilleHouse